services:
  moddb-comment-notifier:
    container_name: moddb-comment-notifier
    image: ghcr.io/tosox/moddb-comment-notifier:latest
    restart: always
    volumes:
      - /srv/moddb-comment-notifier:/app/config
